# .circleci/config.yml
version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: 14.2.0
    steps:
      # ...
      - run: bundle exec fastlane beta
      
workflows:
  build-test-adhoc:
    jobs:
      - build-and-test
